# Generated by Django 3.1.7 on 2021-03-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
