# Generated by Django 3.1.7 on 2021-03-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210316_1816'),
        ('main_app', '0005_auto_20210316_1805'),
    ]

    operations = [
    ]
