# Generated by Django 3.1.7 on 2021-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20210316_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default='2021-03-16 00:00', verbose_name='Comment Date'),
        ),
    ]
