# Generated by Django 3.1.7 on 2021-03-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210316_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Comment Date'),
        ),
    ]
