# Generated by Django 3.1.7 on 2021-03-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210318_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.review'),
        ),
    ]
