# Generated by Django 3.1.7 on 2021-03-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210318_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewPhoto',
        ),
    ]
